package it.acsoftware.hyperiot.websocket.model.message;

public enum HyperIoTWebSocketMessageType {
    AUDIO_DATA("AUDIO"),
    VIDEO_DATA("VIDEO"),
    APPLICATION("APPLICATION"),
    CONNECTION_OK("CONNECTION_OK"),
    DISCONNECTING("DISCONNECTING"),
    OK("OK"),
    ERROR("ERROR"),
    RESULT("RESULT"),
    HEARTBEAT("HEARTBEAT"),
    INFO("INFO"),
    PARTICIPANT_ADDED("PARTICIPANT_ADDED"),
    PARTICIPANT_GONE("PARTICIPANT_GONE"),
    PARTICIPANT_KICKED("PARTICIPANT_KICKED"),
    PARTICIPANT_BANNED("PARTICIPANT_BANNED"),
    PARTICIPANT_UNBANNED("PARTICIPANT_UNBANNED"),
    PING("PING"),
    PONG("PONG"),
    WEBSOCKET_POLICY_WARNING("WEB_SOCKET_POLICY_WARNING"),
    SET_ENCRYPTION_KEY("SET_ENCRYPTION_KEY"),
    SET_CHANNEL_ENCRYPTION_KEY("SET_CHANNEL_ENCRYPTION_KEY"),
    WARNING("WARNING");
    private String type;

    private HyperIoTWebSocketMessageType(String type) {
        this.type = type;
    }
}
